apiVersion: v1
kind: ConfigMap

metadata:
  name: task-management-config

data:
  PORT: "CHANGE_ME"
  CA_CERT_PATH: "CHANGE_ME"
  CONNECTION_LIMIT: "CHANGE_ME"
  DB_HOST: "CHANGE_ME"
  DB_NAME: "CHANGE_ME"
  DB_PORT: "CHANGE_ME"
  DB_URL: "CHANGE_ME"
  SSL_MODE: "CHANGE_ME"