apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ingress-nginx.yaml
  - metrics-server.yaml

patches:
  - path: ingress-controller-node-selector.yaml
  - path: metrics-server-patch.yaml